Repository WordPress/wp-feature-notifications, pull requests merged in 2023-04, with the labels that each got.

#211 build: add lint-staged
  .husky/pre-commit
  lint-staged.config.cjs
  package-lock.json
  package.json
Labels: [Type] development tools

#215 test: fix `test-unit-php` script in package.json
  package.json
Labels: bug

#210 chore: add languages directory
  languages/.gitkeep
  wp-feature-notifications.php
Labels: i18n

#219 chore: update `@wordpress/scripts`
  package-lock.json
  package.json
Labels: bug, [Type] development tools

#213 ci: refactor github workflows
  .github/actions/node/action.yml
  .github/actions/php/action.yml
  .github/workflows/coding-standards.yml
  .github/workflows/node-build.yml
  .github/workflows/node-ci.yml
  .github/workflows/php-ci.yml
  .github/workflows/test-suite.yml
  .prettierrc.js
Labels: [Type] development tools

#237 removes unnecessary packages
  package-lock.json
  package.json
Labels: dependencies

#240 187 Release action
  .distignore
  .github/workflows/release.yml
  .gitignore
  build/wp-notify.asset.php
  build/wp-notify.css
  build/wp-notify.js
  src/stories/Dash-multiple.stories.js
  src/stories/Dash-single.stories.js
  src/stories/Hub-multiple.stories.js
  src/stories/Hub-single.stories.js
Labels: [Type] Project Management

#243 Replace feature request template with yaml version
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/Feature_request.yml
Labels: [Type] Project Management

#244 Update dependabot config to reduce noise
  .github/dependabot.yml
Labels: [Type] development tools

#236 update to react 18 (converts createElement to createRoot)
  .wp-env.json
  package-lock.json
  package.json
  readme.txt
  src/scripts/wp-notify.js
Labels: dependencies, javascript

#248 build: add typescript
  package-lock.json
  package.json
Labels: [Type] development tools

#252 Drawer update
  .editorconfig
  .eslintrc.js
  .lintstagedrc
  .stylelintrc
  includes/demo.php
  includes/restapi/fake_api.json
  jsconfig.json
  package-lock.json
  package.json
  src/scripts/components/Drawer.js
  src/scripts/components/Notice.js
  src/scripts/components/NoticeAction.js
  src/scripts/components/NoticeEmpty.js
  src/scripts/components/NoticeHubFooter.js
  src/scripts/components/NoticeHubSectionHeader.js
  src/scripts/components/NoticeImage.js
  src/scripts/components/NoticeMeta.js
  src/scripts/components/NoticesArea.js
  src/scripts/components/NoticesLoop.js
  src/scripts/components/NotificationHub.js
  src/scripts/components/NotificationHubIcon.js
  src/scripts/demo.js
  src/scripts/demo/index.js
  src/scripts/index.js
  src/scripts/store/actions.js
  src/scripts/store/constants.js
  src/scripts/store/controls.js
  src/scripts/store/index.js
  src/scripts/store/reducer.js
  src/scripts/store/selectors.js
  src/scripts/store/utils.js
  src/scripts/utils/drawer.js
  src/scripts/utils/effects.js
  src/scripts/utils/guards.js
  src/scripts/utils/index.js
  src/scripts/utils/init.js
  src/scripts/utils/sanitization.js
  src/stories/Dash-multiple.stories.js
  src/stories/Dash-single.stories.js
  src/stories/Hub-multiple.stories.js
  src/stories/Hub-single.stories.js
  src/styles/notify/components/bullet.scss
  src/styles/notify/dashboard/notice.scss
  src/styles/notify/hub/admin-bar.scss
  src/styles/notify/hub/elements.scss
  src/styles/notify/hub/layout.scss
  src/styles/notify/hub/notice.scss
  src/styles/notify/notify.scss
  src/styles/notify/vars.scss
  src/styles/wp-notifications.scss
  src/styles/wp-notify.css
  src/styles/wp-notify.js
  src/wp-notifications.js
  src/wp-notify.js
  tsconfig.eslint.json
  tsconfig.json
  types/global.d.ts
  webpack.config.js
Labels: [Scope] User Interface

#278 build: add eslint import order rules
  .eslintrc.js
  src/scripts/components/Drawer.js
  src/scripts/components/Notice.js
  src/scripts/components/NoticeAction.js
  src/scripts/components/NoticeHubFooter.js
  src/scripts/components/NoticeHubSectionHeader.js
  src/scripts/components/NoticeImage.js
  src/scripts/components/NoticesArea.js
  src/scripts/components/NotificationHub.js
  src/scripts/demo/index.js
  src/scripts/store/controls.js
  src/scripts/store/index.js
  src/scripts/store/selectors.js
  src/scripts/utils/index.js
  src/scripts/utils/init.js
Labels: [Type] development tools

#277 refactor: Drawer width logic
  src/scripts/components/Drawer.js
Labels: [Scope] User Interface

#279 fix: eslint config for tests directory
  .eslintrc.js
  storybook/stories/Hub-empty.stories.jsx
  storybook/stories/Hub-multiple.stories.jsx
  storybook/stories/Hub-single.stories.jsx
  storybook/stories/docs/databaseSchema.stories.mdx
  storybook/stories/docs/internalApi.stories.mdx
  storybook/stories/docs/restApi.stories.mdx
  storybook/stories/docs/translations.stories.mdx
  tests/jse2e/main.test.js
  tests/jsunit/main.test.js
  tsconfig.eslint.json
Labels: [Type] development tools

#255 ci: remove php 7.2 add 8.1 and 8.2
  .github/actions/php/action.yml
  .github/workflows/coding-standards.yml
  .github/workflows/node-build.yml
  .github/workflows/test-suite.yml
Labels: [Type] development tools

#282 fix: storybook json import
  storybook/stories/Dash-multiple.stories.jsx
  storybook/stories/Hub-multiple.stories.jsx
Labels: bug

#256 build: update composer packages
  composer.json
  composer.lock
Labels: [Type] development tools

#283 fix: rest api namespace
  includes/restapi/class-notification-controller.php
  src/scripts/constants.js
Labels: [Scope] Service

#284 fix: remove SMS and App from demo settings options
  includes/demo.php
Labels: [Scope] User Interface, demo

#285 fix(mvp): Stage 1 - clean php includes
  includes/class-aggregate-factory.php
  includes/class-base-notification.php
  includes/class-factory.php
  includes/exceptions/class-failed-to-add-recipient.php
  includes/exceptions/class-invalid-recipient.php
  includes/exceptions/class-invalid-type.php
  includes/image/interface-image.php
  includes/interface-json-unserializable.php
  includes/interface-notification.php
  includes/interface-status.php
  includes/messages/class-aggregate-factory.php
  includes/messages/class-base-factory.php
  includes/messages/class-base-message.php
  includes/messages/interface-factory.php
  includes/messages/interface-message.php
  includes/persistence/class-wpdb-notification-repository.php
  includes/persistence/interface-notification-repository.php
  includes/recipients/class-aggregate-factory.php
  includes/recipients/class-base-factory.php
  includes/recipients/class-collection.php
  includes/recipients/class-role.php
  includes/recipients/class-user.php
  includes/recipients/interface-factory.php
  includes/recipients/interface-recipient.php
  includes/senders/class-base-sender.php
  includes/senders/interface-factory.php
  includes/senders/interface-sender.php
  tests/phpunit/includes/bootstrap.php
  tests/phpunit/includes/class-dummy-message.php
  tests/phpunit/tests/test-base-message.php
  tests/phpunit/tests/test-base-notification.php
  tests/phpunit/tests/test-factory.php
  tests/phpunit/tests/test-notification-repository.php
  tests/phpunit/tests/test-recipient-collection.php
  tests/phpunit/tests/test-role-recipient.php
  tests/phpunit/tests/test-user-recipient.php
  wp-feature-notifications.php
Labels: php

#296 Simplify and combine editorconfig
  .editorconfig
Labels: [Type] development tools

#289 feature(mvp): Stage 2 - add initial model classes
  composer.json
  composer.lock
  includes/helper/class-serde.php
  includes/model/class-channel.php
  includes/model/class-message.php
  includes/model/class-notification.php
  includes/model/class-subscription.php
  tests/phpunit/tests/model/test-model-channel.php
  tests/phpunit/tests/model/test-model-message.php
  tests/phpunit/tests/model/test-model-notification.php
  tests/phpunit/tests/model/test-model-subscription.php
  wp-feature-notifications.php
Labels: [Scope] Model

#290 feature(mvp): Stage 3 - add initial factory classes
  includes/factory/class-message.php
  includes/factory/class-notification.php
  includes/factory/class-subscription.php
  includes/framework/class-factory.php
  tests/phpunit/includes/bootstrap.php
  tests/phpunit/includes/class-test-case.php
  tests/phpunit/includes/class-testcase.php
  tests/phpunit/tests/factory/test-factory-message.php
  tests/phpunit/tests/factory/test-factory-notification.php
  tests/phpunit/tests/factory/test-factory-subscription.php
  tests/phpunit/tests/model/test-model-channel.php
  tests/phpunit/tests/model/test-model-message.php
  tests/phpunit/tests/model/test-model-notification.php
  tests/phpunit/tests/model/test-model-subscription.php
  wp-feature-notifications.php
Labels: [Scope] Model

#178 feature(mvp): Stage 4 add item and collection schemas to rest api
  includes/restapi/class-notification-controller.php
  tests/phpunit/tests/rest-api/test-notification-controller.php
Labels: [Scope] Service

#309 fix: storybook fake api data
  storybook/fake_api.json
  storybook/stories/Dash-multiple.stories.jsx
  storybook/stories/Hub-multiple.stories.jsx
Labels: bug

#310 refactor: initially render bell icon server side
  includes/load.php
  src/scripts/components/NotificationHub.js
  src/scripts/components/NotificationHubIcon.js
  src/styles/hub/admin-bar.scss
Labels: [Scope] UI - Notification Hub
